### ISSUE TITLE
Renombrar el archivo a README.md

### ISSUE THREAD

**Issue by juanbono** [pdep-utn-frd/presentacion-2022-YanetGelhorn#1]
Hola, para que aparezca el texto apenas entras al repositorio es necesario que el archivo que tiene extension `md` se llame README.md (al llamarse `presentacionYanetGelhorn.md` no se muestra). Por lo que deberias renombrar o subir el archivo con ese nombre.

**Comment by YanetGelhorn** [comment]
Ya lo hice, muchas gracias!

**Comment by juanbono** [comment]
Buenisimo, cierro el issue!
